version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ibds-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ibds
    ports:
      - "5433:5432" # host:container
    volumes:
      - ibds_pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    container_name: ibds-adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  ibds_pgdata:
    driver: local

